### PR TITLE
use github import paths as they always work and mumble.info does not

### PR DESCRIPTION
**Pull request by HorayNarea**

### CODE REVIEW

**Comment by bontibon** [comment]
This could just be fixed by updating mumble.info's HTTPS certificate. In the mean time, you could pass `-insecure` to `go get`:

    go get -insecure -u mumble.info/grumble/cmd/grumble

**Comment by HorayNarea** [comment]
I know but why not just use the github paths?
The source is hosted here and mumble.info has no informations about grumble other than "it exists"

also: i personally find it more logical that import-paths point directly to where the source "lives"  but thats just my opinion :)

**Comment by HorayNarea** [comment]
another argument to merge this PR: https://github.com/mumble-voip/grumble/issues/4#issuecomment-215698490

**Comment by mkrautz** [comment]
Fixed SSL for the apex mumble.info. This should work w/o any changes now.

**Comment by HorayNarea** [comment]
No it doesn't:
```
go get -v -u mumble.info/grumble/cmd/grumble       
Fetching https://mumble.info/grumble/cmd/grumble?go-get=1
Parsing meta tags from https://mumble.info/grumble/cmd/grumble?go-get=1 (status code 404)
package mumble.info/grumble/cmd/grumble: unrecognized import path "mumble.info/grumble/cmd/grumble" (parse https://mumble.info/grumble/cmd/grumble?go-get=1: no go-import meta tags)
```

**Comment by mkrautz** [comment]
Sorry. When I tested it, I "accidently" did `go get mumble.info/grumble` first ... which, of course, fetches the repo and makes everything work.

I'll fix it.

**Comment by mkrautz** [comment]
Should be fixed now, can you confirm?

Also, thank you for taking the time to author the patch! But I'd like to keep the current mumble.info URLs.

**Comment by HorayNarea** [comment]
Yes it's working, thank you!

**Pull request closed without merging**
