### PR TITLE
Vendor all dependencies used in the code base

### PR DESCRIPTION
**Pull request by olabiniV2**
Vendoring of dependencies make it significantly easier to make sure that the code doesn't stop working when someone updates the master of one of the dependencies. Another solution would be to use modules, but since these are still fairly new, it might be better to use vendoring, since it's support by several older Golang versions.

### CODE REVIEW

**Comment by davidebeatrici** [comment]
@sorcix I see you added a "thumbs down" reaction. Could you explain what's wrong with the pull request, please?

**Comment by kroppt** [comment]
On the modules front, it's not as though the older versions of Go would break, it just wouldn't do anything with the module files. Go 1.11 is the first version supporting modules, which came out mid-2018, using `GO111MODULE` and default for later versions. That seems like a long time to me.
For stable branches:
go1.13
- Chocolatey
- scoop
- Arch
- snap
- Fedora
- CentOS

go1.12
- Ubuntu
- Gentoo

go1.11
- Raspberry Pi
- Debian

One negative of vendoring is that you need to have all the dependencies in duplicate version control, whereas modules are cached once per version (even from installing other Go applications).

**Comment by actown** [comment]
With go modules being supported for a while now along with having CI testing go 1.14.x we should consider #61 instead of this.

Developers working on the project can use https://github.com/moovweb/gvm to setup a go 1.14 install if they do not have a recent go version in their package manager. Hopefully in the future we can start shipping prebuilt binaries for end users.

Thoughts @olabiniV2 and @kroppt.

**Comment by davidebeatrici** [comment]
#61 merged.

**Pull request closed without merging**
